# Generated by Django 4.2.2 on 2023-06-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=10)),
                ('em', models.CharField(max_length=20)),
                ('sub', models.CharField(max_length=100)),
                ('mes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='mypics/')),
                ('img1', models.ImageField(upload_to='mypics1/')),
            ],
        ),
    ]
