# Generated by Django 4.2.2 on 2023-06-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('eads', models.CharField(max_length=100)),
                ('mnb', models.CharField(max_length=100)),
                ('esub', models.CharField(max_length=100)),
                ('ym', models.CharField(max_length=100)),
            ],
        ),
    ]
